# Generated by Django 6.0.6 on 2026-07-03 01:46

import django.db.models.deletion
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=60, verbose_name='Batch no')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.item')),
            ],
            options={
                'verbose_name_plural': 'batches',
            },
        ),
        migrations.CreateModel(
            name='CostLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField()),
                ('qty_received', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='stock.batch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='catalog.item')),
                ('source_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_lots', to='docs.documentline')),
            ],
            options={
                'ordering': ['received_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('CONSIGNED', 'On consignment'), ('EXPIRED', 'Expired'), ('UNFIT', 'Unfit'), ('DISPOSED', 'Disposed')], max_length=10)),
                ('qty', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.batch')),
                ('consignment_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.costlot')),
            ],
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('CONSIGNED', 'On consignment'), ('EXPIRED', 'Expired'), ('UNFIT', 'Unfit'), ('DISPOSED', 'Disposed')], max_length=10)),
                ('qty_delta', models.IntegerField()),
                ('at', models.DateTimeField(db_index=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.batch')),
                ('consignment_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.customer')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='docs.document')),
                ('document_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='docs.documentline')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.costlot')),
            ],
            options={
                'ordering': ['at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('item', 'batch_no'), name='uniq_item_batch_no'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', 0)), name='stock_never_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Coalesce('batch', 0), models.F('lot'), models.F('zone'), django.db.models.functions.comparison.Coalesce('consignment_customer', 0), models.F('item'), name='uniq_balance_key'),
        ),
    ]
