# Generated by Django 6.0.6 on 2026-07-03 00:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Company name')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Address')),
                ('tin', models.CharField(blank=True, max_length=30, verbose_name='TIN')),
                ('tax_regime', models.CharField(choices=[('VAT', 'VAT'), ('TOT', 'TOT (turnover tax)'), ('NONE', 'None')], default='VAT', max_length=4, verbose_name='Tax regime')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='VAT rate %')),
                ('tot_rate', models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='TOT rate %')),
                ('prices_tax_exclusive', models.BooleanField(default=True, verbose_name='Prices entered tax-exclusive')),
                ('withholding_on_sales', models.BooleanField(default=False, verbose_name='Withholding on sales')),
                ('withholding_on_purchases', models.BooleanField(default=False, verbose_name='Withholding on purchases')),
                ('withholding_rate', models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Withholding rate %')),
                ('near_expiry_months', models.PositiveSmallIntegerField(default=6, verbose_name='Near-expiry months')),
                ('consignment_term_months', models.PositiveSmallIntegerField(default=3, verbose_name='Consignment term (months)')),
                ('default_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Default credit limit')),
                ('default_credit_action', models.CharField(choices=[('WARN', 'Warn and allow'), ('BLOCK', 'Block (owner may override)')], default='WARN', max_length=5, verbose_name='Default credit action')),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(choices=[(1, 'Meskerem'), (2, 'Tikimt'), (3, 'Hidar'), (4, 'Tahsas'), (5, 'Tir'), (6, 'Yekatit'), (7, 'Megabit'), (8, 'Miyazya'), (9, 'Ginbot'), (10, 'Sene'), (11, 'Hamle'), (12, 'Nehase')], default=11, verbose_name='Fiscal year starts (Ethiopian month)')),
                ('date_display', models.CharField(choices=[('GREGORIAN', 'Gregorian'), ('ETHIOPIAN', 'Ethiopian'), ('BOTH', 'Both')], default='GREGORIAN', max_length=10, verbose_name='Date display')),
            ],
            options={
                'verbose_name': 'Company settings',
            },
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=20, unique=True)),
                ('next_no', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('entity', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=50)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
