# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="numbersequence",
            name="doc_type",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
