# Generated by Django 6.0.6 on 2026-07-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companysettings_print_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='phone',
            field=models.CharField(blank=True, help_text='Shown on printed documents.', max_length=100, verbose_name='Phone numbers'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='print_layout',
            field=models.CharField(choices=[('COMPACT', 'Compact'), ('DETAILED', 'Detailed'), ('SALES_ATT', 'Cash sales attachment')], default='COMPACT', max_length=9, verbose_name='Print layout'),
        ),
    ]
