# Generated by Django 6.0.6 on 2026-07-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companysettings_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='discounts_enabled',
            field=models.BooleanField(default=True, help_text='Off hides both the document and line discount boxes.', verbose_name='Discounts in use'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='fiscal_machine_present',
            field=models.BooleanField(default=True, help_text='Off hides the machine-total box on sales.', verbose_name='Fiscal machine present'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='sale_price_editable',
            field=models.BooleanField(default=False, help_text="On lets staff type a price on sales, proformas and consignment issues instead of taking the item's price (reverses D80 — discounts are the safer way to charge less).", verbose_name='Sale price editable at the time of sale'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='unit_conversion_enabled',
            field=models.BooleanField(default=True, help_text='Off hides the factor box; every line counts in base units.', verbose_name='Pack conversion (factor) in use'),
        ),
    ]
