# Generated by Django 6.0.6 on 2026-08-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_companysettings_discounts_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='negative_balance_policy',
            field=models.CharField(choices=[('ALLOW', 'Allowed — flagged on the Finance page'), ('BLOCK_VOID', 'Not when voiding'), ('BLOCK_POSTING', 'Never — refuse the posting')], default='ALLOW', help_text='Allowed: a negative balance is a warning on the Finance page, not an error — it means income or an opening balance has not been recorded yet. Not when voiding: day-to-day entry stays unrestricted, but a void may not push an account below zero. Never: any posting that would overdraw an account is refused.', max_length=14, verbose_name='Cash and bank may go negative'),
        ),
    ]
