# Generated by Django 6.0.6 on 2026-08-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_companysettings_negative_balance_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='negative_balance_policy',
            field=models.CharField(choices=[('ALLOW', 'Allowed — flagged on the Finance page'), ('BLOCK_VOID', 'Not when voiding'), ('BLOCK_POSTING', 'Never — refuse the posting')], default='ALLOW', help_text='What happens when a payment would take an account below zero. Allowed: it goes through and the account shows red on the Finance page — usually it means income or an opening balance was never entered. Not when voiding: staff are never stopped, but voiding an old document may not overdraw an account. Never: any payment larger than the balance is refused.', max_length=14, verbose_name='Cash and bank may go negative'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='sale_price_editable',
            field=models.BooleanField(default=False, help_text="On lets staff type a price on sales, proformas and consignment issues instead of using the item's price. A discount is the safer way to charge less: it leaves a record of the reduction.", verbose_name='Sale price editable at the time of sale'),
        ),
    ]
