# Generated by Django 6.0.8 on 2026-08-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_companysettings_negative_balance_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='books_closed_through',
            field=models.DateField(blank=True, help_text='Leave empty until you start closing months. Once set, documents dated on or before this day can no longer be voided or corrected — a void reverses the money today but removes the document from the month it was in, so a report you have already printed and filed would quietly change. Move the date forward each time you finish a month.', null=True, verbose_name='Books closed through'),
        ),
    ]
