# Generated by Django 6.0.8 on 2026-09-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companysettings_books_closed_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='filter_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
