# Generated by Django 6.0.8 on 2026-08-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companysettings_books_closed_through'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='unit_conversion_enabled',
        ),
    ]
