# Generated by Django 6.0.8 on 2026-09-12 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_filter_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='backup_interval_days',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = every day, which is the recommendation. Higher means fewer backups and more work at risk. Backing up more than once a day needs the Windows task changed on the PC.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Back up every (days)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='backup_keep_count',
            field=models.PositiveSmallIntegerField(default=14, help_text='Older ones are removed, except the newest of each month, which is kept for a year. The newest good backup is never removed.', validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(365)], verbose_name='Nightly backups kept'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='backup_primary_path',
            field=models.CharField(blank=True, help_text='Where finished backups are kept. Blank = the folder the deployment already uses. Full path, e.g. D:\\NarcosBackups.', max_length=300, verbose_name='Primary backup folder'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='backup_secondary_path',
            field=models.CharField(blank=True, help_text='A second copy, on another drive or a USB stick. Blank = none. If the drive is missing the backup still succeeds and the run warns.', max_length=300, verbose_name='Second copy folder'),
        ),
    ]
