# Generated by Django 6.0.6 on 2026-07-03 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_delta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('at', models.DateTimeField(db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='money_rows', to='catalog.account')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='money_rows', to='docs.document')),
            ],
            options={
                'ordering': ['at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_made', to='docs.document')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations_received', to='docs.document')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer'), ('CHEQUE', 'Cheque')], default='CASH', max_length=13)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.account')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_lines', to='docs.document')),
            ],
        ),
        migrations.CreateModel(
            name='WithholdingLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('RECEIVABLE', 'Tax office owes us'), ('PAYABLE', 'We owe the tax office')], max_length=10)),
                ('amount_delta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('certificate_no', models.CharField(blank=True, max_length=60)),
                ('at', models.DateTimeField(db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withholding_rows', to='docs.document')),
            ],
            options={
                'ordering': ['at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PartyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier')], max_length=8)),
                ('party_id', models.PositiveBigIntegerField()),
                ('amount_delta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('at', models.DateTimeField(db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_rows', to='docs.document')),
            ],
            options={
                'ordering': ['at', 'pk'],
                'indexes': [models.Index(fields=['party_type', 'party_id'], name='money_party_party_t_9f3285_idx')],
            },
        ),
    ]
