# Generated by Django 6.0.6 on 2026-07-03 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_label', models.CharField(max_length=50)),
                ('factor', models.PositiveIntegerField(default=1)),
                ('qty_entered', models.PositiveIntegerField()),
                ('qty_base', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit_cost_entered', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('free_qty', models.PositiveIntegerField(default=0)),
                ('line_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_taxable', models.BooleanField(default=True)),
                ('cogs_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('qty_sold', models.PositiveIntegerField(default=0)),
                ('qty_returned', models.PositiveIntegerField(default=0)),
                ('qty_expired_unfit', models.PositiveIntegerField(default=0)),
                ('target_zone', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LotConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('RECEIVING', 'Receiving'), ('SALE', 'Sale'), ('PROFORMA', 'Proforma'), ('CONSIGNMENT_ISSUE', 'Consignment issue'), ('CONSIGNMENT_SETTLEMENT', 'Consignment settlement'), ('CUSTOMER_RETURN', 'Customer return'), ('SUPPLIER_RETURN', 'Supplier return'), ('CUSTOMER_PAYMENT', 'Customer payment'), ('SUPPLIER_PAYMENT', 'Supplier payment'), ('WHT_REMITTANCE', 'Withholding remittance'), ('TRANSFER', 'Transfer'), ('EXPENSE', 'Expense'), ('ZONE_MOVE', 'Zone move'), ('ADJUSTMENT', 'Adjustment'), ('STOCK_COUNT', 'Stock count'), ('OPENING_STOCK', 'Opening stock'), ('OPENING_AR', 'Opening receivable'), ('OPENING_AP', 'Opening payable'), ('OPENING_CASH', 'Opening cash'), ('OPENING_CONSIGNMENT', 'Opening consignment'), ('OPENING_EXPIRED', 'Opening expired/unfit')], max_length=25)),
                ('doc_no', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOIDED', 'Voided')], default='DRAFT', max_length=6)),
                ('document_date', models.DateTimeField(blank=True, null=True)),
                ('sale_kind', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CREDIT', 'Credit')], max_length=6)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('supplier_invoice_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('doc_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taxable_base', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('exempt_base', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_rate_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('withholding_expected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('withheld_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('withholding_certificate_no', models.CharField(blank=True, max_length=60)),
                ('fiscal_receipt_no', models.CharField(blank=True, max_length=60)),
                ('machine_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payee', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='catalog.customer')),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.expensecategory')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='catalog.account')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_posted', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='catalog.supplier')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='catalog.account')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_voided', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_taxable', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='docs.document')),
            ],
        ),
    ]
