# Generated by Django 6.0.6 on 2026-07-03 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('docs', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentline',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.batch'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='docs.document'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item'),
        ),
        migrations.AddField(
            model_name='lotconsumption',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_consumptions', to='docs.documentline'),
        ),
        migrations.AddField(
            model_name='lotconsumption',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='stock.costlot'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_type', 'status'], name='docs_docume_doc_typ_cfdba5_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('doc_no__isnull', False)), fields=('doc_type', 'doc_no'), name='uniq_doc_no_per_type'),
        ),
    ]
