# Generated by Django 6.0.6 on 2026-07-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='posted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
