# Generated by Django 6.0.6 on 2026-07-03 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_document_posted_at'),
        ('stock', '0002_stockledger_is_reversal'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentline',
            name='batch_no_entered',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='documentline',
            name='expiry_entered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentline',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock.costlot'),
        ),
    ]
