# Generated by Django 6.0.6 on 2026-07-03 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_documentline_batch_no_entered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='customer_will_withhold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='related_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_documents', to='docs.document'),
        ),
    ]
