# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0005_document_customer_will_withhold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentline",
            name="qty_delta",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="documentline",
            name="source_zone",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
