# Generated by Django 6.0.6 on 2026-07-28 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='correction_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='document',
            name='corrects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='docs.document'),
        ),
    ]
