# Generated by Django 6.0.6 on 2026-08-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_document_correction_reason_document_corrects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment due date'),
        ),
    ]
