# Generated by Django 6.0.6 on 2026-07-03 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank')], max_length=4, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('tin', models.CharField(blank=True, max_length=30, verbose_name='TIN')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Address')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Blank = company default.', max_digits=14, null=True, verbose_name='Credit limit')),
                ('credit_action', models.CharField(blank=True, choices=[('WARN', 'Warn and allow'), ('BLOCK', 'Block (owner may override)')], help_text='Blank = company default.', max_length=5, null=True, verbose_name='When over limit')),
                ('is_withholding_agent', models.BooleanField(default=False, help_text='PLCs, government, NGOs — they keep back the withholding % when paying.', verbose_name='Withholding agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'expense categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Cost')),
                ('purchase_date', models.DateField(verbose_name='Purchase date')),
                ('useful_life_years', models.PositiveSmallIntegerField(verbose_name='Useful life (years)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('category', models.CharField(choices=[('DRUG', 'Drug'), ('REAGENT', 'Reagent'), ('SUPPLY', 'Medical supply'), ('EQUIPMENT', 'Equipment')], default='DRUG', max_length=10, verbose_name='Category')),
                ('is_batch_tracked', models.BooleanField(default=True, verbose_name='Batch tracked')),
                ('has_expiry', models.BooleanField(default=True, verbose_name='Has expiry')),
                ('vat_exempt', models.BooleanField(default=False, help_text='Medicines are VAT-exempt by law — confirm with your accountant.', verbose_name='VAT exempt')),
                ('base_unit', models.CharField(default='unit', help_text='The unit stock is counted in, e.g. "pack of 10".', max_length=50, verbose_name='Base unit')),
                ('generic_name', models.CharField(blank=True, max_length=200, verbose_name='Generic name')),
                ('dosage_form', models.CharField(blank=True, max_length=100, verbose_name='Dosage form')),
                ('strength', models.CharField(blank=True, max_length=100, verbose_name='Strength')),
                ('pack_description', models.CharField(blank=True, max_length=200, verbose_name='Pack description')),
                ('maintained_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Selling price')),
                ('pricing_mode', models.CharField(choices=[('MANUAL', 'Maintained price'), ('AUTO', 'Auto: cost + margin %')], default='MANUAL', max_length=6, verbose_name='Pricing mode')),
                ('auto_margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Auto margin %')),
                ('min_margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Low-margin alert %')),
                ('reorder_level', models.PositiveIntegerField(blank=True, null=True, verbose_name='Reorder level')),
                ('shelf_bin', models.CharField(blank=True, max_length=50, verbose_name='Shelf/bin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('tin', models.CharField(blank=True, max_length=30, verbose_name='TIN')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_label', models.CharField(max_length=50, verbose_name='Unit label')),
                ('factor_to_base', models.PositiveIntegerField(verbose_name='Units of base per 1')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='catalog.item')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'unit_label'), name='uniq_item_unit_label'), models.CheckConstraint(condition=models.Q(('factor_to_base__gt', 1)), name='unit_factor_gt_1')],
            },
        ),
    ]
