# Generated by Django 6.0.6 on 2026-07-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customer',
            name='license_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='License no.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, verbose_name='Mobile'),
        ),
    ]
