# Generated by Django 6.0.8 on 2026-08-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_customer_city_customer_license_no_customer_mobile'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemunit',
            name='uniq_item_unit_label',
        ),
        migrations.RemoveConstraint(
            model_name='itemunit',
            name='unit_factor_gt_1',
        ),
        migrations.DeleteModel(
            name='ItemUnit',
        ),
    ]
